project_id = "pvzokvhoxysbgutkxlbx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.blaze-history]
verify_jwt = false