// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvzokvhoxysbgutkxlbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2em9rdmhveHlzYmd1dGt4bGJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0ODYzNzIsImV4cCI6MjA3MTA2MjM3Mn0.nxXmSovzVQqqoBAJtiFCx182t6cdP2wg4LOWApM-XDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});